### ISSUE TITLE
Charges and Fields Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/charges-and-fields#32]
## Design
- [x] **Design doc created** (Date: 12/02/2014 ) 
  - [x] Make phethelp@gmail.com owner, share with phet-team
  - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: / / )
- [x] **Design concept complete**  (Date: 02/05/2015)
- [x] **Wireframes complete** (Date: 05/25/2015 ) 
- [x] **Mockups complete** (Date: 05/25/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 04/29/2015 ) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 05/11/2015) 
  - [x] Performance acceptable
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Check compatible activities  
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Compatible activities ([author spreadsheet](https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Update [Gooru spreadsheet](https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [x] Sim primer (Being tracked in #116)
  - [x] Verify credits
- [x] Add to Edmodo
## Implementation
- [x] **Sim repo created** (Date: 10/16/2014 ) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme fil 
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Existing sim tested for bugs, issues reported in repo
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 10/17 /2014)
- [x] **Sim feature complete** (Date: 04/15/2015) 
- [x] **Code review complete** (Date: 06/21/2015) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 09/06/2016 ) 
  - [x] Update repo README to published template
## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 08/26/2016)
- [x] **First release candidate** (Date: 08/29/2016) 
  - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
  - [x] Test matrix deemed complete

Note - counting "RC.6" as the first release candidate in this case. Over 100 commits were done after the initial RCs in summer of 2015, so the RC process was rebooted

**Comment by ariel-phet** [comment]
Assigning to @arouinfar for pre-publication items and interviews section

Self assigning to go through other items

**Comment by arouinfar** [comment]
CAF is now live. Teacher Tips will be up later tonight, and the remaining checklist items will be taken care of soon.

**Comment by ariel-phet** [comment]
@arouinfar all remaining items (notes in design doc, primer, and compatible activities) are in your court.

**Comment by arouinfar** [comment]
Compatible activities have already been moved over, so I've checked that off. Hoping to get the interview notes moved over today. Primer will be awhile...

**Comment by ariel-phet** [comment]
@arouinfar understood on primer

**Comment by veillette** [comment]
Since create primer is being tracked separately in #116, this issue can be closed.
