### ISSUE TITLE
Legacy TODO cleanup

### ISSUE THREAD

**Issue by andrewadare** [phetsims/charges-and-fields#91]
There are many leftover TODO comments in C&F. Now that the sim has had many testing rounds for performance, appearance, and memory handling, many appear obsolete, leaving code quality as the primary remanining consideration. Each of these will be assessed in turn:
- [x] ChargesAndFieldsModel.js:
  45:     // @public - Because we need to export our tandem for now. TODO!
  46      this.tandem = tandem;
- [x]   73:       chargesAndSensorsEnclosureBounds: new Bounds2( -1.25, -2.30, 1.25, -1.70 ) // TODO: should not be initialized? meters
- [x]   86:         // TODO: improved way to do this without separate properties? How to handle layout?
- [x] ChargesAndFieldsMeasuringTapeNode.js:
  35:       dragBounds: availableModelBoundsProperty.value, // TODO: does this get updated?
- [x] ChargesAndFieldsScreenView.js:
  218:       // TODO: do we want additional padding?
  219        model.chargesAndSensorsEnclosureBounds.set( modelViewTransform.viewToModelBounds( chargesAndSensorsPanel.bounds ) );
- [x] ChargesAndSensorsPanel.js:
  97:           // TODO: have it look up where to animate to WHEN it needs to animate?
  98            var initialViewPosition = previewNode.getUniqueTrailTo( screenView ).getAncestorMatrix().timesVector2( Vector2.ZERO );  
- [x] ElectricFieldArrowCanvas.js:
  26:   // TODO: Add Bounds scale?
  27    var scaledPaddedBounds = new Bounds2( arrowShape.bounds.minX \* scale,
  28                                          arrowShape.bounds.minY \* scale,
- [x] ElectricFieldCanvasNode.js:
  56      // Invalidate paint on a bunch of changes
  57:     // TODO: cleanup listener duplication for "something changed" emitter?
  58      var invalidateSelfListener = this.invalidatePaint.bind( this );
- [x]   72:     // TODO: rename modelPositions? (and in other views?)
  73      this.positions = []; // {Array.<Vector2>}
- [x]  166:         // TODO: matrix operation should be simpler here, and we can hard-code it?
  167          context.translate( viewPosition.x, viewPosition.y );
  168          context.rotate( -electricField.angle() );
- [x] ElectricFieldSensorNode.js:
  55:     this.modelElement = electricFieldSensor; // TODO: what is using this? public/private?
- [ ] ElectricPotentialMobileWebGLNode.js:
  160:       // TODO: reduce allocations
  161        var projectionMatrixInverse = new Matrix3().set( projectionMatrix ).invert();
- [x] ElectricPotentialSensorNode.js:
  76:     // TODO: private/public? Can't rename yet
  77      this.modelElement = electricPotentialSensor;

**Comment by andrewadare** [comment]
This set of commits clears most of the TODOs. Two remain: the tandem assignment in ChargesAndFieldsModel (see #90), and a matrix inversion optimization.

Regarding the latter: after all the work done on #83, performance of this sim is now very good, so  evidently the allocations in ElectricPotentialMobileWebGLNode are not causing significant problems. I will leave the TODO in place for now in case @jonathanolson (or someone else with expertise/interest) wishes to revisit that.

**Comment by andrewadare** [comment]
The open TODO has been given its own ticket (#105) and marked with the lowest priority.
